# Generated by Django 4.1.4 on 2023-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_profile_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resim',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
