# Generated by Django 4.1.4 on 2023-07-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resim',
            field=models.FileField(default='avatar.png', null=True, upload_to=''),
        ),
    ]
