# Generated by Django 4.1.4 on 2023-07-22 09:47

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_profile_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resim',
            field=models.FileField(default=chat.models.Profile.default_image, null=True, upload_to=''),
        ),
    ]
