# Generated by Django 4.1.4 on 2023-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_profile_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resim',
            field=models.FileField(default='media/avatar.png', upload_to=''),
        ),
    ]
